Repository usegalaxy-eu/infrastructure-playbook, pull requests merged in 2023-09, with the labels that each got.

#881 freebayes: Dynamic memory allocation
  files/galaxy/tpv/tools.yml
Labels: enhancement

#883 change celery setting
  group_vars/celerycluster.yml
Labels: enhancement

#882 diamond: Add loc file for manual database updates
  files/galaxy/config/tool_data_table_conf.xml
Labels: enhancement

#887 concat: Remove revision 855580142a12 from migrated_tools_conf.xml
  files/galaxy/config/migrated_tools_conf.xml
Labels: bug

#888 freebayes_wrapper: Comment revision 33a0e6aca936 from migrated_tools_conf.xml
  files/galaxy-test/config/migrated_tools_conf.xml
Labels: bug

#890 dna_methylation: Comment out in tool_conf.xml.j2
  templates/galaxy/config/tool_conf.xml.j2
Labels: bug

#891 Rebalance JWDs
  templates/galaxy/config/object_store_conf.xml.j2
Labels: bug

#893 Revert "Rebalance JWDs"
  templates/galaxy/config/object_store_conf.xml.j2
Labels: bug

#903 Global Climate Strike on September 15th 2023 TPV rule: consider ongoing trainings only
  files/galaxy/tpv/tool_defaults.yml
Labels: bug

#909 trinity: Remove `-XX:MaxPermSize=2G` from `_JAVA_OPTIONS`
  files/galaxy/tpv/tools.yml
Labels: bug

#910 Bump usegalaxy_eu.rustus version to 0.3.0
  requirements.yaml
Labels: dependencies

#915 Add Singularity GPU destination, decrease requirements for helixer
  files/galaxy/tpv/destinations.yml.j2
  files/galaxy/tpv/tools.yml
Labels: enhancement
